apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-gateway
  template:
    metadata:
      labels:
        app: bots-gateway
    spec:
      containers:
        - name: bots-gateway
          image: ilya02il/bots-gateway:latest
          env:
          - name: GRPC_CHAT_BOT_SRV_CONNECTION
            value: "http://chat-bots-clusterip-srv:666"
          - name: TG_BOT_TOKEN
            value: "5263166008:AAEnSw0_oYrZjzaQPQ3xuV0C9EYGjTjEqmc"
          - name: HOST
            value: "https://1ccf-171-33-248-232.jp.ngrok.io"

---

apiVersion: v1
kind: Service
metadata:
  name: bots-gateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: bots-gateway
  ports:
  - name: bots-gateway
    protocol: TCP
    port: 80
    targetPort: 80