apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-bots-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bots-service
  template:
    metadata:
      labels:
        app: chat-bots-service
    spec:
      containers:
        - name: chat-bots-service
          image: ilya02il/chat-bot-service:latest
          env:
          - name: SQL_SERVER_CONNECTION
            value: "Server=tcp:common-mssql-clusterip-srv,1433;Database=ChatBotServiceDb;uid=sa;password=93phCKFh_;MultipleActiveResultSets=true;"
          - name: REDIS_CONNECTION
            value: "redis-clusterip-srv:6379"
          - name: GRPC_SCHEDULE_SRV_CONNECTION
            value: "http://schedules-clusterip-srv:666"
          - name: WEB_API_PORT
            value: "80"
          - name: GRPC_PORT
            value: "666"
          
---

apiVersion: v1
kind: Service
metadata:
  name: chat-bots-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: chat-bots-service
  ports:
  - name: chat-bots-service
    protocol: TCP
    port: 80
    targetPort: 80
  - name: chat-bots-grpc
    protocol: TCP
    port: 666
    targetPort: 666