apiVersion: v1
kind: Deployment
metadata:
  name: chat-bots-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bots-mssql
  template:
    matadata:
      labels:
        app: chat-bots-mssql
    spec:
      containers:
        - name: chat-bots-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          -name: SA_PASSWORD
            valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-claim

---

apiVersion: v1
kind: Service
metadata:
  name: chat-bots-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: chat-bots-mssql
  ports:
  - name: chat-bots-mssql
    protocol: TCP
    port: 1433
    targetPort: 1433

---

apiVersion: v1
kind: Service
metadata:
  name: chat-bots-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: chat-bots-mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
