# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: schedule-mssql-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 200Mi

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: identity-mssql-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 200Mi

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: chat-bot-mssql-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 200Mi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi